name: Hourly YouTube Counter

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - next_hour

permissions:
  contents: write

concurrency:
  group: hourly-youtube-counter
  cancel-in-progress: false

jobs:
  counter:
    runs-on: ubuntu-latest

    timeout-minutes: 70

    steps:

      # =========================
      # CHECKOUT
      # =========================

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0


      # =========================
      # PYTHON
      # =========================

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # =========================
      # DEPENDENCIES
      # =========================

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # =========================
      # YOUTUBE TOKEN
      # =========================

      - name: Create token
        env:
          TOKEN: ${{ secrets.YT_TOKEN }}
        run: |
          printf '%s' "$TOKEN" > token.json


      # =========================
      # COUNTER
      # =========================

      - name: Run counter
        id: counter
        continue-on-error: true
        run: |
          python counter.py


      # =========================
      # SAVE HISTORY
      # =========================

      - name: Save history
        if: always()
        continue-on-error: true
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add history.json

          if git diff --cached --quiet; then
            echo "No history changes."
          else
            git commit -m "Update subscriber history"

            git pull --rebase origin main || true

            git push origin main || true
          fi


      # =========================
      # WAIT ONE HOUR
      # =========================

      - name: Wait one hour
        if: always()
        run: |
          echo "Prochaine vidéo dans environ 1 heure..."
          sleep 3600


      # =========================
      # START NEXT RUN
      # =========================

      - name: Start next run
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Démarrage de la prochaine run..."

          curl --fail-with-body \
            -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type":"next_hour"}'

          echo "Prochaine run déclenchée." 
